### ISSUE TITLE
C matrix in the SLIS model

### ISSUE THREAD

**Issue by JunsolKim** [jin530/SWalk#2]
https://github.com/jin530/SWalk/blob/b561da44daaa621270575adeca9a079fe084b940/algorithms/swalk/swalk.py#L125

Thank you so much for sharing the source code! 

I have a question about the role of `C` matrix at `Line 125`. From my understanding, `input_matrix` is identical to `target_matrix` in the SLIS model, so `C` always becomes a zero matrix. Thus, I wonder if we can just remove `C` and `np.diag(C)` from the code.

**Comment by jin530** [comment]
Thank you for your comment!

As you mentioned, we can remove C from the code. 
(It is needed for other models we experimented with but are not used anymore.)
