### ISSUE TITLE
How to load saved model, and predict on new data?

### ISSUE THREAD

**Issue by iFe1er** [jin530/SWalk#4]
For SWalk model, after training on train_full.txt, model parameter(such as matrix SLIS.p and part_SLIT.p) , are saved in data_ckpt/.

Now I have a new test data (let's say it called NEW_TEST.txt, most of its' session_id & item_id had already appeared in train_full.txt), how could I load the model in data_ckpt/SLIS.p to inference NEW_TEST.txt and get next item predictions with scores?

I notice that in session-rec repo, there is a Saver.py(https://github.com/rn5l/session-rec/blob/d5aca66cb45030c93b7cc4d26253b0ef66f232ef/evaluation/metrics/saver.py) so how to use saver to generate output for NEW_TEST.txt ? 

Or is there other way to generate prediction on NEW_TEST.txt ?

Thanks!

**Comment by iFe1er** [comment]
@jin530 I would appreciate if you could offer some help

**Comment by jin530** [comment]
After the training, the final model is self.enc_w, i.e., the item-item relevance matrix.

So, you have to load the learned self.enc_w to infer new test data; for example, you can use 'self.model_path' to save and load it in Swalk. 

I hope it will be helpful.
